services:
  app:
    image: hello-front-dev1
    environment:
      VITE_BACKEND_URL: http://server:3000
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: hello-front-dev1 # This will name the container hello-front-dev 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy1
    depends_on:
      - app # wait for the frontend container to be started