PUT http://localhost:3000/todos/68a8447dc42374138d74e39a HTTP/1.1
content-type: application/json

{
    "text": "kamote",
    "done": false
}

###
POST http://localhost:3000/todos/ HTTP/1.1
content-type: application/json

{
    "text": "kamote12",
    "done": false
}

###
GET http://localhost:3000/todos/ HTTP/1.1
content-type: application/json
###
GET http://localhost:3000/todos/statistics HTTP/1.1
content-type: application/json